# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-12 19:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20160512_1943'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mood',
            old_name='user',
            new_name='userProfile',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='friends',
            field=models.ManyToManyField(blank=True, related_name='friends', to=settings.AUTH_USER_MODEL),
        ),
    ]
