# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-01-14 17:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_mood_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
